### ISSUE TITLE
Can token caching be simplified to singleton dependency injection?

### ISSUE THREAD

**Issue by xstof** [Azure-Samples/ms-identity-aspnet-daemon-webapp#25]
The [part of this sample which showcases a client-credential flow whereby the Sync Controller fetches a token](https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/master/UserSync/Controllers/SyncController.cs#L55-L66), leverages a custom cache implementation.  (A "cache of the cache" as a matter of speaking.)  This is done by [wrapping the MSAL token cache](https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/master/UserSync/Controllers/SyncController.cs#L62) in another custom cache implementation called "[MSALAppTokenMemoryCache](https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/master/UserSync/Utils/MSALAppTokenMemoryCache.cs#L35)".

This seems overly complex for the scenario at hand.  (There is no need for a redirect url in a client cred flow, so we have all information at hand to construct the IConfidentialClientApplication on beforehand.)

Can we instead simplify this and construct the IConfidentialClientApplication just once at startup and from there, inject it into the controller as a singleton dependency?  This would allow to leverage the MSAL built-in token cache directly without the need for a custom implementation.

This would require the call to "[AcquireTokenForClient](https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/master/UserSync/Utils/MSALAppTokenMemoryCache.cs#L35)" to be thread safe though; which is not something which is explicitly [documented](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractacquiretokenparameterbuilder-1.executeasync?view=azure-dotnet#Microsoft_Identity_Client_AbstractAcquireTokenParameterBuilder_1_ExecuteAsync).

Thanks for your help in shaping clarity around this. /cc @jmprieur

**Comment by TiagoBrenck** [comment]
Hi @xstof 
I would like to correct one thing in your statement. We don't have a "cache of the cache", and this is not the purpose of "MSALAppTokenMemoryCache". What we have is a class that knows where to storage MSAL cache, I would call it a cache provider. "MSALAppTokenMemoryCache" stores and retrieve it on memory. Other option could be SQL for example. 

MSAL cache itself cannot take the decision where it will be stored, otherwise we would be restricting the developers to one single technology.

About the singleton idea for IConfidentialClientApplication, it could be possible but needs to be tested in an extremelly concurrent scenario.

**Comment by xstof** [comment]
Fully aligned.  The need for testing in a concurrent scenario; is that because of IConfidentialClientApplication not being designed as thread-safe? Or is it?  

Because if thread-safe, I’d expect this to be a valid and simplified approach.  (We are dealing with a client cred flow, so even in high concurrency/load, the token will likely come from cache for majority of requests and the refresh would only happen occasionally upon exporation).

**Comment by TiagoBrenck** [comment]
There is a thread about the singleton going on in the engineering team, so I will let you know when I get more info about it

**Comment by jmprieur** [comment]
The recommendation is now to use ASP.NET Core with Microsoft.Identity.Web
See https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2
