### ISSUE TITLE
Sample is old and does no build 

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/ms-identity-aspnet-daemon-webapp#32]
.net core sample: https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2
It does not make sense for a web app to be a daemon app?
I am not able to build this in VS 2019. ADO pipeline is broken. 

Can we deprecate it? @jmprieur

**Comment by jennyf19** [comment]
@jmprieur what's the plan w/this?

**Comment by jmprieur** [comment]
The sample builds now (CI build green)

@kalyankrishna1 do we want to deprecate it?
