### ISSUE TITLE
Lot of errors

### ISSUE THREAD

**Issue by anilSimon123** [Azure-Samples/ms-identity-aspnet-daemon-webapp#33]
Hi,

I followed the exact steps. I havent touched the code except for client id and app secret. But the build isnt happening because of the errors. Is there something i should install or any packages to be added?

Here are the errors i am getting

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	25	Active
Error	CS0246	The type or namespace name 'ITokenCache' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALAppTokenMemoryCache.cs	42	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALAppTokenMemoryCache.cs	59	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALAppTokenMemoryCache.cs	72	Active
Error	CS0246	The type or namespace name 'ITokenCache' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	42	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	50	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	60	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	71	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	80	Active
Error	CS0234	The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	25	Active
Error	CS0246	The type or namespace name 'IConfidentialClientApplication' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	129	Active
Error	CS0103	The name 'ConfidentialClientApplicationBuilder' does not exist in the current context	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	130	Active

**Comment by anilSimon123** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	25	Active
Error	CS0246	The type or namespace name 'ITokenCache' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALAppTokenMemoryCache.cs	42	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALAppTokenMemoryCache.cs	59	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALAppTokenMemoryCache.cs	72	Active
Error	CS0246	The type or namespace name 'ITokenCache' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	42	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	50	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	60	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	71	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Utils\MSALUserTokenMemoryCache.cs	80	Active
Error	CS0234	The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	25	Active
Error	CS0246	The type or namespace name 'IConfidentialClientApplication' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	129	Active
Error	CS0103	The name 'ConfidentialClientApplicationBuilder' does not exist in the current context	UserSync	C:\graph\active-directory-dotnet-daemon-v2\UserSync\Controllers\AccountController.cs	130	Active

**Comment by TiagoBrenck** [comment]
@anilSimon123 could you try cleaning the solution and building it again? I am confused about the errors because in mentions "C:\graph\\**active-directory-dotnet-daemon-v2**" but this is not the correct sample. This one is **ms-identity-aspnet-daemon-webapp**.

I have cloned it on my machine and I couldnt get these errors.

**Comment by anilSimon123** [comment]
Tried again...but still getting the same errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Controllers\AccountController.cs	25	Active
Error	CS0246	The type or namespace name 'ITokenCache' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALAppTokenMemoryCache.cs	42	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALAppTokenMemoryCache.cs	59	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALAppTokenMemoryCache.cs	72	Active
Error	CS0246	The type or namespace name 'ITokenCache' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALUserTokenMemoryCache.cs	42	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALUserTokenMemoryCache.cs	50	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALUserTokenMemoryCache.cs	60	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALUserTokenMemoryCache.cs	71	Active
Error	CS0246	The type or namespace name 'TokenCacheNotificationArgs' could not be found (are you missing a using directive or an assembly reference?)	UserSync	C:\csharp graph\ms-identity-aspnet-daemon-webapp\UserSync\Utils\MSALUserTokenMemoryCache.cs	80	Active

**Comment by jmprieur** [comment]
@anilSimon123 would it be a path length issue with some nuget packages
do you want to try to rename the ms-identity-aspnet-daemon-webapp project to webapp ?

**Comment by anilSimon123** [comment]
You mean the whole project? or should i do something like reinstall the nuget packages?

**Comment by jmprieur** [comment]
I just mean that you might want to move the code closer to the root of the hard drive, and then restore the nuget packages. Sometimes there are very long nuget packages, and they fail to restore (with no explicit message).
