### ISSUE TITLE
Sample of exposing own secured api and calling via daemon app on its own name

### ISSUE THREAD

**Issue by rupeshprasad-adi** [Azure-Samples/ms-identity-aspnet-daemon-webapp#41]
There is an example of exposing own api and consuming via daemon app for .net core but not for asp.net 
a sample for same would be great.
.Net core sample can be found here. 
https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2

**Comment by jmprieur** [comment]
@kalyankrishna1 
BTW, we have a backlog item to provide Ms.Id.Web for ASP.NET (but it's very low on the priority list)

**Comment by rupeshprasad-adi** [comment]
Is there any time line when it will be available if not then some example/sample code or article would be great. 
Also if possible would you be able to let me know what i need to change in this archived repo. This is something i am currently using in PROD system. 
https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity/tree/master

**Comment by TiagoBrenck** [comment]
Hello @rupeshprasad-adi 

Have you tried coding it yet and got any error or blocked?

The code in this repo may not be compatible with .NET Standard, but the concept explain on the readme applies for both. You are looking at registering an application for the API and adding app roles in the manifest. Then you register another application for the deamon, configuring these app roles as application permissions, and when consuming the API in your code, you must use the `/.default` as scope.

The archived sample is using ADAL, where we recommend you to use MSAL instead. That change will be on the deamon side only and the process of instantiating a `ConfidentialClientApplication` will be the same as this .net core console sample. I believe that the WebAPI code in the archived sample might be re-usable as well.

**Comment by jmprieur** [comment]
This sample exists here: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi
