### ISSUE TITLE
Non-expiring secrets not supported any more

### ISSUE THREAD

**Issue by NeedsCoffee** [Azure-Samples/ms-identity-aspnet-daemon-webapp#62]
In the line 123 of the readme it suggests creating a secret that might not expire - this is not possible as non-expiring secrets were deprecated some time ago...

https://github.com/Azure-Samples/ms-identity-aspnet-daemon-webapp/blob/2515242f22bdeffd76bbd37b0601fa62676e74cf/README.md?plain=1#L123

**Comment by aremo-ms** [comment]
Updated README.md to match latest portal UI. We will update generator once get to this sample
