### ISSUE TITLE
the example does not work with personal email

### ISSUE THREAD

**Issue by huyvo98** [Azure-Samples/ms-identity-aspnet-daemon-webapp#7]
Hi,

I am trying to build a daemon service that integrates with outlook 365. I have to use my personal email since my work email does not have admin privileges. However, it seems that the authentication service only work with work and school email right now. It complains that my log in email is not work or school email, even though I have Azure 's subscription (trial) and set up tenant, etc. Is it the current limitation or did I missed any steps?

Thanks,
Huy Vo

**Comment by kalyankrishna1** [comment]
@huyvo98  please share the domain of the email address you are trying to use (the part after @)

**Comment by huyvo98** [comment]
Hi Kalyan,

Thanks for the response. So I cannot test the app with personal email then. one question, with admin consent authorization, can I get and subscribe emails from one employee mailbox?

Thanks,
huy vo
